# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='repairer',
            managers=[
            ],
        ),
    ]
