# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20160913_0149'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='repairer',
            name='location',
        ),
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='repairer',
            name='latitude',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='repairer',
            name='longitude',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
