# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20160923_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='location',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='username',
        ),

        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=200, primary_key=True),
        ),
    ]
