# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20160924_0302'),
    ]

    operations = [

    ]
