# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_auto_20160926_0429'),
    ]

    operations = [

    ]
