# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_auto_20160926_0500'),
    ]

    operations = [

        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=200, primary_key=True),
        ),
    ]
