# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_auto_20160926_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairer',
            name='shopid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first.Shop'),
        ),
        migrations.AddField(
            model_name='shop',
            name='id',
            field=models.IntegerField(default=0, serialize=False, verbose_name='ID'),
        ),
    ]
