# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-27 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0014_auto_20160927_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='r_username',
            field=models.CharField(max_length=100),
        ),
    ]
