# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-30 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0016_auto_20160928_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='latitude',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='longitude',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='repairer',
            name='latitude',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='repairer',
            name='longitude',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
