# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-17 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0017_auto_20160930_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrating',
            name='r_username',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='repairerrating',
            name='c_username',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
